// <auto-generated />
using System;
using FoodSafetyInspectionTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodSafetyInspectionTracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("FollowUps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ClosedDate = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 6,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 9,
                            Status = 3
                        },
                        new
                        {
                            Id = 4,
                            DueDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            ClosedDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 15,
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 18,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            DueDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 21,
                            Status = 3
                        },
                        new
                        {
                            Id = 8,
                            DueDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 24,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            ClosedDate = new DateTime(2026, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 5,
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            DueDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 8,
                            Status = 1
                        });
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PremisesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PremisesId");

                    b.ToTable("Inspections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InspectionDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Clean and well maintained.",
                            Outcome = 1,
                            PremisesId = 1,
                            Score = 92
                        },
                        new
                        {
                            Id = 2,
                            InspectionDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Minor hygiene issues.",
                            Outcome = 2,
                            PremisesId = 2,
                            Score = 75
                        },
                        new
                        {
                            Id = 3,
                            InspectionDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Serious food storage issue.",
                            Outcome = 3,
                            PremisesId = 3,
                            Score = 48
                        },
                        new
                        {
                            Id = 4,
                            InspectionDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good record keeping.",
                            Outcome = 1,
                            PremisesId = 4,
                            Score = 88
                        },
                        new
                        {
                            Id = 5,
                            InspectionDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cleaning schedule incomplete.",
                            Outcome = 2,
                            PremisesId = 5,
                            Score = 68
                        },
                        new
                        {
                            Id = 6,
                            InspectionDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cross-contamination risk found.",
                            Outcome = 3,
                            PremisesId = 6,
                            Score = 40
                        },
                        new
                        {
                            Id = 7,
                            InspectionDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Excellent compliance.",
                            Outcome = 1,
                            PremisesId = 7,
                            Score = 95
                        },
                        new
                        {
                            Id = 8,
                            InspectionDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Temperature log missing.",
                            Outcome = 2,
                            PremisesId = 8,
                            Score = 71
                        },
                        new
                        {
                            Id = 9,
                            InspectionDate = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Poor pest control evidence.",
                            Outcome = 3,
                            PremisesId = 9,
                            Score = 52
                        },
                        new
                        {
                            Id = 10,
                            InspectionDate = new DateTime(2026, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "No major issues.",
                            Outcome = 1,
                            PremisesId = 10,
                            Score = 89
                        },
                        new
                        {
                            Id = 11,
                            InspectionDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Staff training records incomplete.",
                            Outcome = 2,
                            PremisesId = 11,
                            Score = 73
                        },
                        new
                        {
                            Id = 12,
                            InspectionDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Unsanitary preparation area.",
                            Outcome = 3,
                            PremisesId = 12,
                            Score = 45
                        },
                        new
                        {
                            Id = 13,
                            InspectionDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "High standard maintained.",
                            Outcome = 1,
                            PremisesId = 1,
                            Score = 94
                        },
                        new
                        {
                            Id = 14,
                            InspectionDate = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Storage labels missing.",
                            Outcome = 2,
                            PremisesId = 2,
                            Score = 78
                        },
                        new
                        {
                            Id = 15,
                            InspectionDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Repeat critical issue.",
                            Outcome = 3,
                            PremisesId = 3,
                            Score = 50
                        },
                        new
                        {
                            Id = 16,
                            InspectionDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Very good hygiene.",
                            Outcome = 1,
                            PremisesId = 4,
                            Score = 91
                        },
                        new
                        {
                            Id = 17,
                            InspectionDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Follow cleaning checklist.",
                            Outcome = 2,
                            PremisesId = 5,
                            Score = 69
                        },
                        new
                        {
                            Id = 18,
                            InspectionDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Improper chilled storage.",
                            Outcome = 3,
                            PremisesId = 6,
                            Score = 43
                        },
                        new
                        {
                            Id = 19,
                            InspectionDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Excellent documentation.",
                            Outcome = 1,
                            PremisesId = 7,
                            Score = 96
                        },
                        new
                        {
                            Id = 20,
                            InspectionDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Corrective action needed.",
                            Outcome = 2,
                            PremisesId = 8,
                            Score = 74
                        },
                        new
                        {
                            Id = 21,
                            InspectionDate = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Multiple non-compliances.",
                            Outcome = 3,
                            PremisesId = 9,
                            Score = 49
                        },
                        new
                        {
                            Id = 22,
                            InspectionDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Compliant.",
                            Outcome = 1,
                            PremisesId = 10,
                            Score = 90
                        },
                        new
                        {
                            Id = 23,
                            InspectionDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Food label update required.",
                            Outcome = 2,
                            PremisesId = 11,
                            Score = 76
                        },
                        new
                        {
                            Id = 24,
                            InspectionDate = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cleaning failures continue.",
                            Outcome = 3,
                            PremisesId = 12,
                            Score = 47
                        },
                        new
                        {
                            Id = 25,
                            InspectionDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Improvement observed.",
                            Outcome = 1,
                            PremisesId = 6,
                            Score = 82
                        });
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.Premises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Premises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Market Street",
                            Name = "Green Farm Cafe",
                            RiskRating = 1,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 River Road",
                            Name = "River Bistro",
                            RiskRating = 2,
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 3,
                            Address = "8 Harbour Lane",
                            Name = "Ocean View Restaurant",
                            RiskRating = 3,
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 4,
                            Address = "21 Main Street",
                            Name = "Sunny Bakery",
                            RiskRating = 1,
                            Town = "Limerick"
                        },
                        new
                        {
                            Id = 5,
                            Address = "9 Mountain Road",
                            Name = "Hilltop Diner",
                            RiskRating = 2,
                            Town = "Waterford"
                        },
                        new
                        {
                            Id = 6,
                            Address = "30 King Street",
                            Name = "Fresh Bites",
                            RiskRating = 3,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 7,
                            Address = "14 Queen Avenue",
                            Name = "City Grill",
                            RiskRating = 1,
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 8,
                            Address = "67 Oak Drive",
                            Name = "Golden Spoon",
                            RiskRating = 2,
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 9,
                            Address = "3 Pine Street",
                            Name = "Happy Meals Cafe",
                            RiskRating = 3,
                            Town = "Limerick"
                        },
                        new
                        {
                            Id = 10,
                            Address = "19 Central Road",
                            Name = "Urban Kitchen",
                            RiskRating = 1,
                            Town = "Waterford"
                        },
                        new
                        {
                            Id = 11,
                            Address = "50 Bridge Street",
                            Name = "Taste Corner",
                            RiskRating = 2,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 12,
                            Address = "88 Lake View",
                            Name = "Family Table",
                            RiskRating = 3,
                            Town = "Cork"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.FollowUp", b =>
                {
                    b.HasOne("FoodSafetyInspectionTracker.Models.Inspection", "Inspection")
                        .WithMany("FollowUps")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.Inspection", b =>
                {
                    b.HasOne("FoodSafetyInspectionTracker.Models.Premises", "Premises")
                        .WithMany("Inspections")
                        .HasForeignKey("PremisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premises");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.Inspection", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("FoodSafetyInspectionTracker.Models.Premises", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
